// OpenAI _client import
using OpenAI.Chat;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace ChatVisual
{
    internal class OpenAIWrapper
    {

        private static readonly string apiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY") ?? throw new InvalidOperationException("OPENAI_API_KEY is not set.");

        /// <summary>
        /// ChatMessage is a class from OpenAI.Chat namespace. It has 4 different subclasses that we can use
        /// 1. SystemChatMessage - Role: system - Instruction for AI
        /// 2. UserChatMessage - Role: user - text message that sent by users
        /// 3. AssistantChatMessage - Role: assistant - The response generated by AI
        /// 4. ToolChatMessage - Role: tool - Result from the tool that AI run
        /// </summary>
        private List<ChatMessage> _chatHistory;

        // OpenAI Client and Options
        private ChatClient _miniClient;
        private ChatClient _fullClient;
        private ChatClient _client;
        private ChatCompletionOptions _options;

        // system prompt
        private string _activeSystemPrompt;



        // Constructor for the OpenAIClient
        public OpenAIWrapper()
        {
            _miniClient = new ChatClient("gpt-5.4-mini", apiKey);
            _fullClient = new ChatClient("gpt-5.4", apiKey);
            _client = _miniClient; // default to mini client, we can change it later based on the request config

            _activeSystemPrompt = null; // default to no system prompt, we can set it later based on the request config
            _chatHistory = new List<ChatMessage>();

            // default model parameters
            _options = new ChatCompletionOptions()
            {
                MaxOutputTokenCount = 1024
            };

        }

        // Async method to send message to OpenAI and get response
        public async Task<string> sendMessage(List<SharedMessage> sharedChatHistory, AIRequestConfig requestConfig)
        {

            // PERFORMANCE CONSIDERATION: at the moment we clear and populate entire chat histor for each request
            _chatHistory.Clear();

            // update the configration for model request
            _options = new ChatCompletionOptions()
            {
                Temperature = requestConfig.Temperature,
                MaxOutputTokenCount = requestConfig.MaxOutputToken,
            };

            // set the configs that not in _options 
            _client = requestConfig.Model == "gpt-5.4" ? _fullClient : _miniClient;


            _activeSystemPrompt = requestConfig.SystemPrompt;
            _chatHistory.Add(new SystemChatMessage(_activeSystemPrompt));


            // the sharedChatHistory has completely different fromat from the List<ChatMessageContentPart> that OpenAI use
            // we need to do conversion
            foreach (SharedMessage sharedMessage in sharedChatHistory)
            {

                List<ChatMessageContentPart> contentParts = new List<ChatMessageContentPart>();
                contentParts.Add(ChatMessageContentPart.CreateTextPart(sharedMessage.Message));

                foreach (byte[] screenshot in sharedMessage.Screenshots)
                {
                    // we have to wrap the byte array into BinaryData because that's the format that OpenAI use for image input
                    BinaryData imageContentPart = BinaryData.FromBytes(screenshot);
                    contentParts.Add(ChatMessageContentPart.CreateImagePart(imageContentPart, "image/png"));
                }


                switch (sharedMessage.Role)
                {
                    case ChatMessageRole.User:
                        _chatHistory.Add(new UserChatMessage(contentParts));
                        break;
                    case ChatMessageRole.Assistant:
                        _chatHistory.Add(new AssistantChatMessage(contentParts));
                        break;
                    default:
                        throw new InvalidOperationException("Invalid chat message role: " + sharedMessage.Role);
                }

            }

            // Retries logic (we try again 3 times with 1000ms delay between trial)
            int maxRetries = 3;
            for (int attempt = 1; attempt <= maxRetries; attempt++)
            {
                try
                {
                    // CompleteChatAsync of OpenAI take the options directly along with entire chatHistory here
                    ChatCompletion chatCompletion = await _client.CompleteChatAsync(_chatHistory, _options);
                    var assistantMessage = chatCompletion.Content[0].Text;

                    return assistantMessage;


                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Attempt {attempt} failed: {ex.Message}");
                    if (attempt == maxRetries) return "Error: " + ex.Message;

                    await Task.Delay(1000); // Wait a bit before retrying
                }
            }


            return "Oopsie daisies the C# is really a dummy";
        }


        // =====================================================================
        // UTILITIES
        // =====================================================================

        /// <summary>
        /// Handle the session cleaning process. Will remove the entire chat history and system prompt
        /// </summary>
        public void SessionCleaning()
        {
            _chatHistory.Clear();
            _activeSystemPrompt = null;
        }

        private BinaryData convertBase64ToBinaryData(string base64)
        {
            byte[] bytes = Convert.FromBase64String(base64);
            return new BinaryData(bytes);
        }
    }
}
