using System;
using System.Collections.Generic;



// OpenAI _client import
using OpenAI.Chat;
using System.Threading.Tasks;


namespace ChatVisual
{
    internal class OpenAIWrapper
    {

        private static readonly string apiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY") ?? throw new InvalidOperationException("OPENAI_API_KEY is not set.");

        /// <summary>
        /// ChatMessage is a class from OpenAI.Chat namespace. It has 4 different subclasses that we can use
        /// 1. SystemChatMessage - Role: system - Instruction for AI
        /// 2. UserChatMessage - Role: user - text message that sent by users
        /// 3. AssistantChatMessage - Role: assistant - The response generated by AI
        /// 4. ToolChatMessage - Role: tool - Result from the tool that AI run
        /// </summary>
        private List<ChatMessage> _chatHistory;

        // OpenAI Client and Options
        private ChatClient _client;
        private ChatCompletionOptions _options;



        // Constructor for the OpenAIClient
        public OpenAIWrapper()
        {
            _client = new ChatClient("gpt-5.4-mini", Environment.GetEnvironmentVariable("OPENAI_API_KEY"));
            _chatHistory = new List<ChatMessage>();

            // model parameter
            _options = new ChatCompletionOptions()
            {
                MaxOutputTokenCount = 1024
            };

        }

        // Async method to send message to OpenAI and get response
        public async Task<string> sendMessage(string message, List<string> screenshots)
        {
            if (screenshots.Count == 0)
            {
                Console.WriteLine("Message sent without screenshot");
                _chatHistory.Add(new UserChatMessage(ChatMessageContentPart.CreateTextPart(message)));
            }
            else
            {
                Console.WriteLine($"Message sent with {screenshots.Count} screenshots");

                List<ChatMessageContentPart> contentParts = new List<ChatMessageContentPart>();

                // add all the screenshots and the text message to contentParts
                contentParts.Add(ChatMessageContentPart.CreateTextPart(message));

                foreach (string screenshot in screenshots)
                {
                    // convert back from base64 to binary data
                    BinaryData imageBinaryData = convertBase64ToBinaryData(screenshot);

                    contentParts.Add(ChatMessageContentPart.CreateImagePart(imageBinaryData, "image/png"));

                }


                // the current contentPart contains a list of binary data of screenshot and a text message.
                _chatHistory.Add(new UserChatMessage(contentParts));


            }


            // OpenAI handle the _chatHistory (pass entire array, OpenAI handle the caching on their backend)
            int maxRetries = 3;
            for (int attempt = 1; attempt <= maxRetries; attempt++)
            {
                try
                {
                    // CompleteChatAsync of OpenAI take the options directly along with entire chatHistory here
                    ChatCompletion chatCompletion = await _client.CompleteChatAsync(_chatHistory, _options);
                    var assistantMessage = chatCompletion.Content[0].Text;

                    _chatHistory.Add(new AssistantChatMessage(ChatMessageContentPart.CreateTextPart(assistantMessage)));
                    return assistantMessage;


                } catch (Exception ex)
                {
                    Console.WriteLine($"Attempt {attempt} failed: {ex.Message}");
                    if (attempt == maxRetries) return "Error: " + ex.Message;

                    await Task.Delay(1000); // Wait a bit before retrying
                }
            }


            return "Oopsie daisies the C# is really a dummy";
        }


        // =====================================================================
        // UTILITIES
        // =====================================================================
        private BinaryData convertBase64ToBinaryData(string base64)
        {
            byte[] bytes = Convert.FromBase64String(base64);
            return new BinaryData(bytes);
        }
    }
}
