using System;
using System.Collections.Generic;



// OpenAI _client import
using OpenAI.Chat;
using System.Threading.Tasks;


namespace ChatVisual
{
    internal class OpenAIWrapper
    {

        private static readonly string apiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY") ?? throw new InvalidOperationException("OPENAI_API_KEY is not set.");

        /// <summary>
        /// ChatMessage is a class from OpenAI.Chat namespace. It has 4 different subclasses that we can use
        /// 1. SystemChatMessage - Role: system - Instruction for AI
        /// 2. UserChatMessage - Role: user - text message that sent by users
        /// 3. AssistantChatMessage - Role: assistant - The response generated by AI
        /// 4. ToolChatMessage - Role: tool - Result from the tool that AI run
        /// </summary>
        private List<ChatMessage> _chatHistory;

        // OpenAI Client and Options
        private ChatClient _miniClient;
        private ChatClient _fullClient;
        private ChatClient _client;
        private ChatCompletionOptions _options;

        // system prompt
        private string _activeSystemPrompt;



        // Constructor for the OpenAIClient
        public OpenAIWrapper()
        {
            _miniClient = new ChatClient("gpt-5.4-mini", apiKey);
            _fullClient = new ChatClient("gpt-5.4", apiKey);
            _client = _miniClient; // default to mini client, we can change it later based on the request config

            _activeSystemPrompt = null; // default to no system prompt, we can set it later based on the request config
            _chatHistory = new List<ChatMessage>();

            // default model parameters
            _options = new ChatCompletionOptions()
            {
                MaxOutputTokenCount = 1024
            };

        }

        // Async method to send message to OpenAI and get response
        public async Task<string> sendMessage(string message, List<string> screenshots, AIRequestConfig requestConfig)
        {

            // update the configration for model request
            _options = new ChatCompletionOptions()
            {
                Temperature = requestConfig.Temperature,
                MaxOutputTokenCount = requestConfig.MaxOutputToken,
            };
            
            // set the configs that not in _options 
            _client = requestConfig.Model == "gpt-5.4" ? _fullClient : _miniClient;

            // update the system prompt too. But a change in system prompt mean we would have to clear the chat history 
            if (requestConfig.SystemPrompt != _activeSystemPrompt)
            {
                _activeSystemPrompt = requestConfig.SystemPrompt;
                // clear the chat history and add the new system prompt
                _chatHistory.Clear();
                _chatHistory.Add(new SystemChatMessage(_activeSystemPrompt));
            }


            if (screenshots.Count == 0)
            {
                Console.WriteLine("Message sent without screenshot");
                _chatHistory.Add(new UserChatMessage(ChatMessageContentPart.CreateTextPart(message)));
            }
            else
            {
                Console.WriteLine($"Message sent with {screenshots.Count} screenshots");

                List<ChatMessageContentPart> contentParts = new List<ChatMessageContentPart>();

                // add all the screenshots and the text message to contentParts
                contentParts.Add(ChatMessageContentPart.CreateTextPart(message));

                foreach (string screenshot in screenshots)
                {
                    // convert back from base64 to binary data
                    BinaryData imageBinaryData = convertBase64ToBinaryData(screenshot);

                    contentParts.Add(ChatMessageContentPart.CreateImagePart(imageBinaryData, "image/png"));

                }


                // the current contentPart contains a list of binary data of screenshot and a text message.
                _chatHistory.Add(new UserChatMessage(contentParts));


            }


            // OpenAI handle the _chatHistory (pass entire array, OpenAI handle the caching on their backend)
            int maxRetries = 3;
            for (int attempt = 1; attempt <= maxRetries; attempt++)
            {
                try
                {
                    // CompleteChatAsync of OpenAI take the options directly along with entire chatHistory here
                    ChatCompletion chatCompletion = await _client.CompleteChatAsync(_chatHistory, _options);
                    var assistantMessage = chatCompletion.Content[0].Text;

                    _chatHistory.Add(new AssistantChatMessage(ChatMessageContentPart.CreateTextPart(assistantMessage)));
                    return assistantMessage;


                } catch (Exception ex)
                {
                    Console.WriteLine($"Attempt {attempt} failed: {ex.Message}");
                    if (attempt == maxRetries) return "Error: " + ex.Message;

                    await Task.Delay(1000); // Wait a bit before retrying
                }
            }


            return "Oopsie daisies the C# is really a dummy";
        }


        // =====================================================================
        // UTILITIES
        // =====================================================================

        /// <summary>
        /// Handle the session cleaning process. Will remove the entire chat history and system prompt
        /// </summary>
        public void SessionCleaning()
        {
            _chatHistory.Clear();
            _activeSystemPrompt = null;
        }

        private BinaryData convertBase64ToBinaryData(string base64)
        {
            byte[] bytes = Convert.FromBase64String(base64);
            return new BinaryData(bytes);
        }
    }
}
